"""create compile_outputs

Revision ID: df0daad1ac8d
Revises: af1f233e2334
Create Date: 2026-06-09 21:38:56.945813

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df0daad1ac8d'
down_revision: str | None = 'af1f233e2334'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compile_outputs',
    sa.Column('compile_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('rel_path', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('etag', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("kind IN ('pdf','log','synctex','aux','other')", name=op.f('ck_compile_outputs_compile_output_kind_valid')),
    sa.ForeignKeyConstraint(['compile_id'], ['compiles.id'], name=op.f('fk_compile_outputs_compile_id_compiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_compile_outputs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compile_outputs')),
    sa.UniqueConstraint('compile_id', 'name', name='uq_compile_output_name')
    )
    op.create_index('ix_compile_outputs_compile_id', 'compile_outputs', ['compile_id'], unique=False)
    op.create_index('ix_compile_outputs_project_created', 'compile_outputs', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_compile_outputs_project_created', table_name='compile_outputs')
    op.drop_index('ix_compile_outputs_compile_id', table_name='compile_outputs')
    op.drop_table('compile_outputs')
    # ### end Alembic commands ###
