"""create documents

Revision ID: bec8287c4664
Revises: 8b301674ef53
Create Date: 2026-06-09 17:32:02.459121

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec8287c4664'
down_revision: str | None = '8b301674ef53'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('size_bytes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_documents_size_bytes_non_negative')),
    sa.CheckConstraint('version >= 0', name=op.f('ck_documents_version_non_negative')),
    sa.ForeignKeyConstraint(['entity_id'], ['tree_entities.id'], name=op.f('fk_documents_entity_id_tree_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_documents_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_project_id', 'documents', ['project_id'], unique=False)
    # ### end Alembic commands ###
    # Backfill: every existing doc tree-entity gets an empty content row.
    op.execute(
        """
        INSERT INTO documents (entity_id, project_id, content, version, size_bytes, created_at, updated_at)
        SELECT t.id, t.project_id, '', 0, 0, now(), now()
        FROM tree_entities t
        WHERE t.type = 'doc'
        AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.entity_id = t.id)
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_project_id', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
