"""create files

Revision ID: be53747ebcf5
Revises: bec8287c4664
Create Date: 2026-06-09 17:48:45.292063

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be53747ebcf5'
down_revision: str | None = 'bec8287c4664'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_files_size_bytes_non_negative')),
    sa.ForeignKeyConstraint(['entity_id'], ['tree_entities.id'], name=op.f('fk_files_entity_id_tree_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_files_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id', name=op.f('pk_files'))
    )
    op.create_index('ix_files_project_id', 'files', ['project_id'], unique=False)
    op.create_index('uq_files_storage_key', 'files', ['storage_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_files_storage_key', table_name='files')
    op.drop_index('ix_files_project_id', table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
