"""create tree_entities

Revision ID: 8b301674ef53
Revises: feb8f5c76b1a
Create Date: 2026-06-09 17:22:01.055258

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b301674ef53'
down_revision: str | None = 'feb8f5c76b1a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree_entities',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('folder', 'doc', 'file', name='tree_entity_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_root', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("NOT is_root OR type = 'folder'", name=op.f('ck_tree_entities_root_is_folder')),
    sa.CheckConstraint("type = 'folder' OR name <> ''", name=op.f('ck_tree_entities_name_not_empty_unless_folder')),
    sa.CheckConstraint('is_root = (parent_id IS NULL)', name=op.f('ck_tree_entities_root_has_no_parent')),
    sa.ForeignKeyConstraint(['parent_id'], ['tree_entities.id'], name=op.f('fk_tree_entities_parent_id_tree_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tree_entities_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tree_entities'))
    )
    op.create_index('ix_tree_parent_id', 'tree_entities', ['parent_id'], unique=False)
    op.create_index('ix_tree_project_id', 'tree_entities', ['project_id'], unique=False)
    op.create_index('uq_tree_one_root_per_project', 'tree_entities', ['project_id'], unique=True, postgresql_where=sa.text('is_root'))
    op.create_index('uq_tree_sibling_name', 'tree_entities', ['parent_id', sa.literal_column('lower(name)')], unique=True)
    # ### end Alembic commands ###
    # Backfill: every existing project gets a root folder (idempotent).
    op.execute(
        """
        INSERT INTO tree_entities (id, project_id, parent_id, type, name, is_root, created_at, updated_at)
        SELECT gen_random_uuid(), p.id, NULL, 'folder'::tree_entity_type, '', true, now(), now()
        FROM projects p
        WHERE NOT EXISTS (
            SELECT 1 FROM tree_entities t WHERE t.project_id = p.id AND t.is_root
        )
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tree_sibling_name', table_name='tree_entities')
    op.drop_index('uq_tree_one_root_per_project', table_name='tree_entities', postgresql_where=sa.text('is_root'))
    op.drop_index('ix_tree_project_id', table_name='tree_entities')
    op.drop_index('ix_tree_parent_id', table_name='tree_entities')
    op.drop_table('tree_entities')
    # ### end Alembic commands ###
    # sa.Enum creates the type implicitly on table create but does not drop it;
    # drop it so a re-upgrade does not collide with an existing type.
    op.execute("DROP TYPE tree_entity_type")
