"""create compiles

Revision ID: af1f233e2334
Revises: be53747ebcf5
Create Date: 2026-06-09 21:17:34.349856

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af1f233e2334'
down_revision: str | None = 'be53747ebcf5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compiles',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('main_file', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('artifact_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_pdf', sa.Boolean(), nullable=False),
    sa.Column('log_excerpt', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','success','failure','timeout','cancelled','error')", name=op.f('ck_compiles_compile_status_valid')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_compiles_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_compiles_requested_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compiles'))
    )
    op.create_index('ix_compiles_job_id', 'compiles', ['job_id'], unique=False)
    op.create_index('ix_compiles_project_created', 'compiles', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_compiles_requested_by', 'compiles', ['requested_by'], unique=False)
    op.create_index('ix_compiles_status', 'compiles', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_compiles_status', table_name='compiles')
    op.drop_index('ix_compiles_requested_by', table_name='compiles')
    op.drop_index('ix_compiles_project_created', table_name='compiles')
    op.drop_index('ix_compiles_job_id', table_name='compiles')
    op.drop_table('compiles')
    # ### end Alembic commands ###
