"""user settings: avatar, editor preferences, email change (spec 59)

Revision ID: fda790a9deeb
Revises: d1e3f7a69c82
Create Date: 2026-06-10 18:44:06.516284

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fda790a9deeb"
down_revision: str | None = "d1e3f7a69c82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar_url", sa.Text(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "editor_preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("pending_email", postgresql.CITEXT(), nullable=True))
    op.add_column("users", sa.Column("email_change_token_hash", sa.Text(), nullable=True))
    op.add_column(
        "users", sa.Column("email_change_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    # Index the token hash for confirm-email-change lookups (partial: only rows
    # with a pending change), and pending_email so duplicate checks are cheap.
    op.create_index(
        "ix_users_email_change_token_hash",
        "users",
        ["email_change_token_hash"],
        unique=False,
        postgresql_where=sa.text("email_change_token_hash IS NOT NULL"),
    )
    op.create_index(
        "ix_users_pending_email",
        "users",
        ["pending_email"],
        unique=False,
        postgresql_where=sa.text("pending_email IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_pending_email", table_name="users")
    op.drop_index("ix_users_email_change_token_hash", table_name="users")
    op.drop_column("users", "email_change_expires_at")
    op.drop_column("users", "email_change_token_hash")
    op.drop_column("users", "pending_email")
    op.drop_column("users", "editor_preferences")
    op.drop_column("users", "avatar_url")
    # ### end Alembic commands ###
